### ISSUE TITLE
Sadly, this fails at the last step of, npm run package

### ISSUE THREAD

**Issue by jradxl** [hayderux/electron-flutter#7]
Sadly, this fails at the last step of, npm run package
No doubt I've missunderstood...

$ npm run package
npm ERR! missing script: package

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jradley/.npm/_logs/2020-08-10T21_57_48_599Z-debug.log

$ cat   /home/jradley/.npm/_logs/2020-08-10T21_57_48_599Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/jradley/.sdkman/candidates/java/20.1.0.r11-grl/languages/js/bin/node',
1 verbose cli   '/home/jradley/.sdkman/candidates/java/20.1.0.r11-grl/languages/js/npm/bin/npm-cli.js',
1 verbose cli   '--nodedir=/home/jradley/.sdkman/candidates/java/20.1.0.r11-grl/languages/js',
1 verbose cli   'run',
1 verbose cli   'package'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.15.0
4 verbose stack Error: missing script: package
4 verbose stack     at run (/home/jradley/.sdkman/candidates/java/20.1.0.r11-grl/languages/js/npm/lib/run-script.js:155:19)
4 verbose stack     at /home/jradley/.sdkman/candidates/java/20.1.0.r11-grl/languages/js/npm/lib/run-script.js:63:5
4 verbose stack     at /home/jradley/.sdkman/candidates/java/20.1.0.r11-grl/languages/js/npm/node_modules/read-package-json/read-json.js:116:5
4 verbose stack     at /home/jradley/.sdkman/candidates/java/20.1.0.r11-grl/languages/js/npm/node_modules/read-package-json/read-json.js:436:5
4 verbose stack     at checkBinReferences_ (/home/jradley/.sdkman/candidates/java/20.1.0.r11-grl/languages/js/npm/node_modules/read-package-json/read-json.js:391:45)
4 verbose stack     at final (/home/jradley/.sdkman/candidates/java/20.1.0.r11-grl/languages/js/npm/node_modules/read-package-json/read-json.js:434:3)
4 verbose stack     at then (/home/jradley/.sdkman/candidates/java/20.1.0.r11-grl/languages/js/npm/node_modules/read-package-json/read-json.js:161:5)
4 verbose stack     at /home/jradley/.sdkman/candidates/java/20.1.0.r11-grl/languages/js/npm/node_modules/read-package-json/read-json.js:382:12
4 verbose stack     at /home/jradley/.sdkman/candidates/java/20.1.0.r11-grl/languages/js/npm/node_modules/graceful-fs/graceful-fs.js:115:16
4 verbose stack     at FSReqCallback.readFileAfterClose (internal/fs/read_file_context.js:61:3)
5 verbose cwd /home/jradley/Documents/programming/flutter-electron/electron-flutter/build
6 verbose Linux 5.4.0-42-generic
7 verbose argv "/home/jradley/.sdkman/candidates/java/20.1.0.r11-grl/languages/js/bin/node" "/home/jradley/.sdkman/candidates/java/20.1.0.r11-grl/languages/js/npm/bin/npm-cli.js" "--nodedir=/home/jradley/.sdkman/candidates/java/20.1.0.r11-grl/languages/js" "run" "package"
8 verbose node v12.15.0
9 verbose npm  v6.13.4
10 error missing script: package
11 verbose exit [ 1, true ]

**Comment by redfox-mx** [comment]
@jradxl  you need to go build/web folder and run 
1 - npm install
2 - npm run package
And it's all. Top directory does not package your app, I'm working it

**Comment by hayderux** [comment]
fixed
